module.exports = option => option.setName('day')
					.setDescription('The day of the week.')
					.addChoice('Sunday', 0)
					.addChoice('Monday', 1)
					.addChoice('Tuesday', 2)
					.addChoice('Wednesday', 3)
					.addChoice('Thursday', 4)
					.addChoice('Friday', 5)
					.addChoice('Saturday', 6)