module.exports = {
	day: require('./day.js'),
	dayReq:require('./dayReq.js'),
	endTime: require('./endTime.js'),
	endTimeReq: require('./endTimeReq.js'),
	length: require('./length.js'),
	lengthReq: require('./lengthReq.js'),
	notes: require('./notes.js'),
	notesReq: require('./notesReq.js'),
	opponent: require('./opponent.js'),
	opponentReq: require('./opponentReq.js'),
	startDate: require('./startDate.js'),
	startDateReq: require('./startDateReq.js'),
	startTime:require('./startTime.js'),
	startTimeReq: require('./startTimeReq.js'),
	team: require('./team.js'),
	teamReq: require('./teamReq.js'),
	title: require('./title.js'),
	titleReq: require('./titleReq.js'),
}